# Generated by Django 6.0.4 on 2026-05-08 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='is_solved',
            new_name='is_resolved',
        ),
    ]
